// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/zxq97/agent/internal/config"
	"github.com/zxq97/agent/internal/httphandler"
	"github.com/zxq97/agent/pkg/log"
)

// Injectors from wire.go:

func initializeHTTPHandler(cfg *config.Config, logger log.Logger) (*httphandler.Handler, error) {
	client, err := provideLLMClient(cfg)
	if err != nil {
		return nil, err
	}
	extractor, err := provideRentalExtractor(client, cfg)
	if err != nil {
		return nil, err
	}
	mapsClient, err := provideMapsClient(cfg)
	if err != nil {
		return nil, err
	}
	location, err := provideTimezone()
	if err != nil {
		return nil, err
	}
	handler, err := provideRentalContextHandler(extractor, mapsClient, location)
	if err != nil {
		return nil, err
	}
	vehiclerequirementExtractor, err := provideRequirementExtractor(client, cfg)
	if err != nil {
		return nil, err
	}
	staticCatalog := provideVehicleCatalog()
	resolver, err := provideVehicleResolver(cfg, client, staticCatalog)
	if err != nil {
		return nil, err
	}
	vehiclerequirementHandler, err := provideVehicleRequirementHandler(vehiclerequirementExtractor, resolver)
	if err != nil {
		return nil, err
	}
	guideClient, err := provideGuideClient(cfg)
	if err != nil {
		return nil, err
	}
	compiler, err := provideSearchCompiler(staticCatalog, cfg)
	if err != nil {
		return nil, err
	}
	capabilityResolver, err := provideCapabilityResolver(client, cfg)
	if err != nil {
		return nil, err
	}
	searchcarHandler, err := provideSearchCarHandler(guideClient, compiler, capabilityResolver)
	if err != nil {
		return nil, err
	}
	searchPolicy := provideSearchPolicy()
	generalreplyHandler, err := provideGeneralReplyHandler(client, cfg)
	if err != nil {
		return nil, err
	}
	vehiclecompareHandler := provideVehicleComparisonHandler()
	rentalrulesHandler, err := provideRentalRulesHandler()
	if err != nil {
		return nil, err
	}
	orchestrator, err := provideOrchestrator(handler, vehiclerequirementHandler, searchcarHandler, searchPolicy, generalreplyHandler, vehiclecompareHandler, rentalrulesHandler)
	if err != nil {
		return nil, err
	}
	router, err := provideIntentRouter(client, cfg)
	if err != nil {
		return nil, err
	}
	store := provideStore()
	service, err := provideWebChatService(orchestrator, router, store)
	if err != nil {
		return nil, err
	}
	httphandlerHandler, err := httphandler.New(service, logger)
	if err != nil {
		return nil, err
	}
	return httphandlerHandler, nil
}
